blog/urls.py
from django.urls import re_path
from django.contrib.auth.decorators import permission_required

from blog.views import BlogListView, BlogDetailView, BlogCreate, BlogUpdate, BlogDelete

urlpatterns = [
    re_path(r'^$', BlogListView.as_view(), name = "blog_index"),
    re_path(r'^(?P<pk>\d+)/detail/$', BlogDetailView.as_view(), name="blog_detail"),
    re_path(r'^add/$', permission_required("blog.add_blog")(BlogCreate.as_view()), name="blog_add"),
    re_path(r'^(?P<pk>\d+)/edit/$', permission_required("blog.change_blog")(BlogUpdate.as_view()), name="blog_edit"),
    re_path(r'^(?P<pk>\d+)/delete/$', permission_required("blog.delete_blog")(BlogDelete.as_view()), name="blog_delete"),
]

broom_trade/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

admin.autodiscover()
urlpatterns = [
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),

    re_path(r'^$', include('main.urls')),
    re_path(r'^guestbook/', include('guestbook.urls')),
    re_path(r'^news/', include('news.urls')),
    re_path(r'^imagepool/', include('imagepool.urls')),
    re_path(r'^categories/', include('categories.urls')),
    re_path(r'^goods/', include('goods.urls')),
    re_path(r'^comments/', include('django_comments.urls')),
    re_path(r'^blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.conf.urls import re_path
from django.contrib.auth.decorators import permission_required

from goods.views import GoodsListView, GoodDetailView, GoodCreate, GoodUpdate, GoodDelete

urlpatterns = [
    re_path(r'^(?P<pk>\d+)/$', GoodsListView.as_view(), name="goods_index"),
    re_path(r'^(?P<pk>\d+)/detail/$', GoodDetailView.as_view(), name="goods_detail"),
    re_path(r'^(?P<pk>\d+)/add/$', permission_required("goods.add_good")(GoodCreate.as_view()), name="goods_add"),
    re_path(r'^(?P<pk>\d+)/edit/$', permission_required("goods.change_good")(GoodUpdate.as_view()), name="goods_edit"),
    re_path(r'^(?P<pk>\d+)/delete/$', permission_required("goods.delete_good")(GoodDelete.as_view()), name="goods_delete"),
]

goods/models.py
from django.db import models
from django_comments.moderation import CommentModerator, moderator
from django.urls import reverse

from sorl.thumbnail import ImageField

from categories.models import Category


class Good(models.Model):
  name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name="Название")
  category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
  description = models.TextField(verbose_name="Краткое описание", blank=True)
  content = models.TextField(verbose_name="Полное описание", blank=True)
  price = models.FloatField(db_index=True, verbose_name="Цена, руб.")
  price_acc = models.FloatField(null=True, blank=True, verbose_name="Цена с учетом скидки, руб.")
  in_stock = models.BooleanField(default=True, db_index=True, verbose_name="Есть в наличии")
  featured = models.BooleanField(default=False, db_index=True, verbose_name="Рекомендуемый")
  image = ImageField(upload_to="goods/list", verbose_name="Основное изображение")

  def save(self, *args, **kwargs):
    try:
      this_record = Good.objects.get(pk=self.pk)
      if this_record.image != self.image:
        this_record.image.delete(save=False)
    except Good.DoesNotExist:
      pass
    super().save(*args, **kwargs)

  def delete(self, *args, **kwargs):
    self.image.delete(save=False)
    super().delete(*args, **kwargs)

  def get_absolute_url(self):
    return reverse("goods_detail", kwargs={"pk": self.pk})

  class Meta:
    verbose_name = "товар"
    verbose_name_plural = "товары"


class GoodImage(models.Model):
  good = models.ForeignKey(Good, on_delete=models.CASCADE)
  image = ImageField(upload_to="goods/detail", verbose_name="Дополнительное изображение")

  def save(self, *args, **kwargs):
    try:
      this_record = GoodImage.objects.get(pk = self.pk)
      if this_record.image != self.image:
        this_record.image.delete(save=False)
    except GoodImage.DoesNotExist:
      pass
    super().save(*args, **kwargs)

  def delete(self, *args, **kwargs):
    self.image.delete(save = False)
    super().delete(*args, **kwargs)

  class Meta:
    verbose_name = "изображение к товару"
    verbose_name_plural = "изображения к товару"


class GoodModerator(CommentModerator):
  email_notification = True

moderator.register(Good, GoodModerator)

goods/forms.py
from django import forms

from goods.models import Good, Category


class GoodForm(forms.ModelForm):

  name = forms.CharField(label="Название")
  category = forms.ModelChoiceField(queryset=Category.objects.all(), label="Категория", empty_label=None)
  description = forms.CharField(label="Краткое описание", required=False)
  content = forms.CharField(label="Полное описание", required=False)
  price = forms.FloatField(label="Цена, руб.")
  price_acc = forms.FloatField(label="Цена с учетом скидки, руб.")
  in_stock = forms.BooleanField(label="Есть в наличии", required=False)
  featured = forms.BooleanField(label="Рекомендуемый", required=False)
  image = forms.ImageField(label="Основное изображение")

  class Meta:
    model = Good
    fields = '__all__'

goods/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView, ContextMixin
from django.views.generic.edit import DeleteView
from django.urls import reverse
from django.contrib import messages
from django.forms.models import inlineformset_factory

from categories.models import Category
from goods.models import Good, GoodImage
from goods.forms import GoodForm
from generic.mixins import CategoryListMixin, PageNumberMixin
from generic.controllers import PageNumberView

# logger = logging.getLogger(__name__)

GoodImagesFormset = inlineformset_factory(Good, GoodImage, can_order=True, fields='__all__')


class SortMixin(ContextMixin):
  sort = "0"
  order = "A"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["sort"] = self.sort
    context["order"] = self.order
    return context

  def make_full_url(self, reverse_url):
      return '{}?page={}&sort={}&order={}'.format(reverse_url,
                                                  self.request.GET["page"],
                                                  self.request.GET["sort"],
                                                  self.request.GET["order"]
                                                  )


class GoodsListView(PageNumberView, ListView, SortMixin, CategoryListMixin):
  model = Good
  template_name = "goods_index.html"
  paginate_by = 2
  cat = None

  def get(self, request, *args, **kwargs):
    if self.kwargs["pk"] == None:
        self.cat = Category.objects.first()
    else:
        self.cat = Category.objects.get(pk=self.kwargs["pk"])
    return super().get(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["category"] = self.cat
    return context

  def get_queryset(self):
    goods = Good.objects.filter(category=self.cat)
    if self.sort == "2":
        if self.order == "D":
            goods = goods.order_by("-in_stock", "name")
        else:
            goods = goods.order_by("in_stock", "name")
    elif self.sort == "1":
        if self.order == "D":
            goods = goods.order_by("-price", "name")
        else:
            goods = goods.order_by("price", "name")
    else:
        if self.order == "D":
            goods = goods.order_by("-name")
        else:
            goods = goods.order_by("name")
    return goods


class GoodDetailView(PageNumberView, DetailView, SortMixin, PageNumberMixin):
    model = Good
    template_name = "good.html"


class GoodCreate(PageNumberView, TemplateView, SortMixin, PageNumberMixin):
    template_name = "good_add.html"
    cat = None
    form = None
    formset = None
    __success_msg = "Товар успешно добавлен"

    def get(self, request, *args, **kwargs):
        if self.kwargs["pk"] is None:
            self.cat = Category.objects.first()
        else:
            self.cat = Category.objects.get(pk = self.kwargs["pk"])
        self.form = GoodForm(initial={"category": self.cat})
        self.formset = GoodImagesFormset()

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.cat
        context["form"] = self.form
        context["formset"] = self.formset
        return context

    def post(self, request, *args, **kwargs):
        self.form = GoodForm(request.POST, request.FILES)
        if self.form.is_valid():
            new_good = self.form.save()
            self.formset = GoodImagesFormset(request.POST, request.FILES, instance = new_good)
            if self.formset.is_valid():
                self.formset.save()
                messages.add_message(request, messages.SUCCESS, self.__success_msg)
                reverse_link = reverse("goods_index", kwargs={"pk": new_good.category.pk})
                return redirect(self.make_full_url(reverse_link))
        if self.kwargs["pk"] is None:
            self.cat = Category.objects.first()
        else:
            self.cat = Category.objects.get(pk=self.kwargs["pk"])
        self.formset = GoodImagesFormset(request.POST, request.FILES)
        return super().get(request, *args, **kwargs)


class GoodUpdate(PageNumberView, TemplateView, SortMixin, PageNumberMixin):
    good = None
    template_name = "good_edit.html"
    form = None
    formset = None
    __success_msg = "Товар успешно изменен"

    def get(self, request, *args, **kwargs):
        self.good = Good.objects.get(pk = self.kwargs["pk"])
        self.form = GoodForm(instance = self.good)
        self.formset = GoodImagesFormset(instance=self.good)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["good"] = self.good
        context["form"] = self.form
        context["formset"] = self.formset
        return context

    def post(self, request, *args, **kwargs):
        self.good = Good.objects.get(pk=self.kwargs["pk"])
        self.form = GoodForm(request.POST, request.FILES, instance = self.good)
        self.formset = GoodImagesFormset(request.POST, request.FILES, instance=self.good)
        if self.form.is_valid():
            self.form.save()
            if self.formset.is_valid():
                self.formset.save()
                messages.add_message(request, messages.SUCCESS, self.__success_msg)
                reverse_link = reverse("goods_index", kwargs={"pk": self.good.category.pk})
                return redirect(self.make_full_url(reverse_link))
        return super().get(request, *args, **kwargs)


class GoodDelete(PageNumberView, DeleteView, SortMixin, PageNumberMixin):
    model = Good
    template_name = "good_delete.html"
    __success_msg = "Товар успешно удален"

    def post(self, request, *args, **kwargs):
        reverse_link = reverse("goods_index", kwargs={"pk": Good.objects.get(pk = kwargs["pk"]).category.pk})
        self.success_url = self.make_full_url(reverse_link)
        messages.add_message(request, messages.SUCCESS, self.__success_msg)
        return super().post(request, *args, **kwargs)

goods/templates/good.html
{% extends "main.html" %}
{% load bbcode_tags %}
{% load comments %}
{% block title %}{{ object.name }} :: {{ object.category.name }}{% endblock %}
{% block main %}
  <h2>{{ object.name }}</h2>
  <p>Категория: {{object.category.name }}</p>
  <div class="good-images">
    <div><img src="{{ object.image.url }}"></div>
    {% for goodimage in object.goodimage_set.all %}
      <div><img src="{{ goodimage.image.url }}"></div>
    {% endfor %}
  </div>
  <div>{{ object.content|bbcode|safe }}</div>
  <p>Цена, руб.: {% if object.price_acc > 0 %}<span class="old-price">{{ object.price }}</span>&nbsp;&nbsp;{{ object.price_acc }}{% else %}{{ object.price }}{% endif %}</p>
  {% if object.in_stock %}
    <p>Нет в наличии.</p>
  {% endif %}
  <p><a href="{% url "goods_index" pk=object.category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a></p>
  <p>&nbsp;</p>
  {% render_comment_list for object %}
  <p>&nbsp;</p>
  {% get_comment_form for object as form %}
  <div class="form">
    <form action="{% comment_form_target %}" method="post">
      {% include "generic/form.html" %}
      <input type="hidden" name="next" value="{% url "goods_detail" pk=object.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}">
      <div class="submit-button"><input type="submit" name="submit" value="Отправить"></div>
    </form>
  </div>
{% endblock %}

goods/templates/good_add.html
{% extends "main.html" %}
{% load thumbnail %}
{% block title %}Добавление товара :: {{ category.name }}{% endblock %}
{% block main %}
  <h2>Добавление товара</h2>
  <div class="form">
    <form action="" method="post" enctype="multipart/form-data">
      {% include "generic/form.html" %}
      {% include "generic/formset.html" %}
      <div class="submit-button"><input type="submit" value="Добавить"></div>
    </form>
  </div>
  <p><a href="{% url "goods_index" pk=category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}"">Назад</a></p>
{% endblock %}

goods/templates/good_delete.html
{% extends "main.html" %}
{% load bbcode_tags %}
{% block title %}Удаление товара :: {{ object.name }}{% endblock %}
{% block main %}
  <h2>Удаление товара</h2>
  <h4>{{ object.name }}</h4>
  <p>Категория: {{object.category.name }}</p>
  <div>{{ object.content|bbcode|safe }}</div>
  <p>Цена, руб.: {% if object.price_acc > 0 %}<span class="old-price">{{ object.price }}</span>&nbsp;&nbsp;{{ object.price_acc }}{% else %}{{ object.price }}{% endif %}</p>
  {% if object.in_stock %}
    <p>Нет в наличии.</p>
  {% endif %}
  {% if object.featured %}
    <p>Рекомендуемый.</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
  <p><a href="{% url "goods_index" pk=object.category.pk%}?page={{ pn }}&sort={{ sort }}&order={{ order }}"">Назад</a></p>
{% endblock %}

goods/templates/good_edit.html
{% extends "main.html" %}
{% block title %}Правка товара :: {{ good.name }}{% endblock %}
{% block main %}
  <h2>Правка товара</h2>
  <div class="form">
    <form action="" method="post" enctype="multipart/form-data">
      {% include "generic/form.html" %}
      {% include "generic/formset.html" %}
      <div class="submit-button"><input type="submit" value="Изменить"></div>
    </form>
  </div>
  <p><a href="{% url "goods_index" pk=good.category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}"">Назад</a></p>
{% endblock %}

goods/templates/goods_index.html
{% extends "main.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% block title %}{{ category.name }}{% endblock %}
{% block main %}
  {% include "generic/messages.html" %}
  <h2>{{ category.name }}</h2>
  {% if perms.goods.add_good %}
    <p><a href="{% url "goods_add" pk=category.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Добавить товар</a></p>
  {% endif %}
  <table class="list-table">
    <tr>
      <th>Миниатюра</th>
      <th><a href="?sort=0&order={% if sort == "0" and order == "A" %}D{% else %}A{% endif %}">
        {% if sort == "0" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Название
      </a></th>
      <th>Описание</th>
      <th><a href="?sort=1&order={% if sort == "1" and order == "A" %}D{% else %}A{% endif %}">
        {% if sort == "1" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Цена, руб.
      </a></th>
      <th><a href="?sort=2&order={% if sort == "2" and order == "A" %}D{% else %}A{% endif %}">
        {% if sort == "2" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Есть в наличии
      </a></th>
      {% if perms.goods.change_good %}
        <th>&nbsp;</th>
      {% endif %}
      {% if perms.goods.delete_good %}
        <th>&nbsp;</th>
      {% endif %}
    </tr>
    {% for object in object_list %}
      <tr>
        <td class="centered"><a href="{% url "goods_detail" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}"><img src="{% thumbnail object.image "200x200" %}"><a></td>
        <td><a href="{% url "goods_detail" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">{{ object.name }}</a></td>
        <td>{{ object.description }}</td>
        <td class="centered">{% if object.price_acc > 0 %}<span class="old-price">{{ object.price }}</span><br>{{ object.price_acc }}{% else %}{{ object.price }}{% endif %}</td>
        <td class="centered">{% if object.in_stock %}+{% endif %}</td>
        {% if perms.page.change_good %}
          <td class="centered"><a href="{% url "goods_edit" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Изменить</a></td>
        {% endif %}
        {% if perms.page.delete_good %}
          <td class="centered"><a href="{% url "goods_delete" pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Удалить</a></td>
        {% endif %}
      </tr>
    {% endfor %}
  </table>
  {% include "generic/pagination.html" %}
{% endblock %}